#include "euler.h"
#include <limits.h>

inline int eval_quadratic(int x, int a, int b);
int test_quadratic(int a, int b, int* primes, int primes_len);
int main(int argc, char** argv);

int eval_quadratic(int x, int a, int b) {
    return (x*x + a*x + b);
}

int test_quadratic(int a, int b, int* primes, int primes_len) {
    // returns the number of consecutive primes generated by the quadratic
    int n = 0;
    // we can find the function's evaluation in the list of primes
    while (binary_search(eval_quadratic(n,a,b), primes, primes_len) != -1)
        ++n;
    return n;
}

int main(int argc, char** argv) {
    int max_a = 0, max_b = 0, max_val = 0;
    int val, c;
    int* primes = find_primes(3000, &c);
    //print_iarray(primes, c);
    for (int b = primes[0]; primes[b] < 1000; ++b) {
        for (int a = -primes[b]; a <= 1000; ++a) {
            val = test_quadratic(a, primes[b], primes, c);
            if (val > max_val) {
                max_val = val;
                max_b = primes[b];
                max_a = a;
            }
        }
    }
    printf("a:%d b:%d n:%d\n", max_a, max_b, max_val);
    printf("a*b: %d\n", max_a*max_b);
    free(primes);
    return 0;
}
